packages:
  - tests
  - guides
  - bootstrap
  - notes/examples
  - examples
  - "@starbeam/*"
  - "@starbeam/*/*/examples"
  - "@types/@domtree/*"
  - "@types/*"
  - guides/reactivity
  - packages
  - packages/*
  - packages/*/tests
